consensus-shipyard/lotus

chain/consensus/mir/manager.go
chain/consensus/mir/state_manager.go
chain/consensus/mir/types.go
cmd/mir-validator/README.md
cmd/mir-validator/checkpoint.go
cmd/mir-validator/main.go
cmd/mir-validator/run.go

- Persist all checkpoints by height in Mir database. 
- Add `CHECKPOINTS_REPO` environmental variable to allow validator to (optionally) persist every Mir checkpoint in files inside the path determined by the variable. 
- Added `--init-height` and `--init-checkpoint` flags to `./mir-validator run` to initialize the validator from a specific checkpoint in the database or provided by fail. 
- Command to import and export to and from a file checkpoints. 
- Update `mir-validator` README.

Add commands to persist and initialize from checkpoint

---

.gitignore
Makefile
cmd/eudico/daemon.go
cmd/eudico/main.go
cmd/eudico/mir.go
cmd/eudico/mirvalidator/cfg.go
cmd/eudico/mirvalidator/checkpoint.go
cmd/eudico/mirvalidator/init.go
cmd/eudico/mirvalidator/run.go
cmd/eudico/mirvalidator/utils.go
cmd/eudico/mirvalidator/validator.go
cmd/mir-validator/main.go
scripts/mir/daemon.sh
scripts/mir/validator.sh

This PR moves the commands available in the `mir-validator` into the `eudico` binary. It also updates the scripts accordingly.

Moves mir-validator commands into eudico command

---

Makefile
cmd/eudico/daemon.go
cmd/eudico/mirvalidator/init.go
cmd/eudico/mirvalidator/utils.go
cmd/mir-validator/README.md
cmd/mir-validator/init.go
cmd/mir-validator/utils.go

This PR includes some housekeeping to start the migration from Lotus to Eudico in preparation for Spacenet upgrade.
- It removes `lotus` and `mir-validator` from `make spacenet`.
- It updates the `mir-validator` README and other references to the binary to use `eudico` instead of `mir-validator`
- It adds the required flags for `--lite` and `--mir-validator` to the eudico binary.

Update Makefile and cmd to use eudico instead of lotus

---

itests/kit/init.go

Without this PR it is not possible to control the logging level in itests: all logged messages are INFO and higher even if you want to customize them via GOLOG_LOG_LEVEL.

Fix logging level in itests

---

node/impl/full.go
node/impl/ipc/ipc.go

Use correct spelling for IPC - https://google.github.io/styleguide/go/decisions#initialisms

Use Go convention for IPC API name

---

itests/kit/ensemble.go
itests/kit/ensemble_presets.go
itests/kit/mir_tools.go
itests/kit/mir_validator.go
itests/kit/node_miner.go
itests/kit/node_validator.go
itests/mir_test.go

This PR introduced `TestValidator` types with embedded `TestMiner`. The goal of this PR is to separate these two types and make Lotus and integration tests and Mir-related tests less coupled.

Separate TestValidator and TestMiner

---

Dockerfile
scripts/docker-eudico-entrypoint.sh

Add support for eudico in `lotus-all-in-one`. It should be usable in the same way but adding support to eudico-specific commands. I've done a successful dry-run of building and running it, but according to how we end up using the it may require additional changes.

Support eudico in docker image

---

itests/kit/mir_tools.go
itests/mir_test.go

It was found (with @matejpavlovic ) that itests disconnected validators can produce blocks even if they are disconnected. Based on that fact, we remove corresponding checks that do not make sense anymore.

Remove check that validators do not mine blocks when disconnected

---

chain/consensus/mir/state_manager.go
itests/kit/ensemble.go
itests/kit/mir_tools.go
itests/mir_test.go

This PR:
- adds more debug information
- refactors waitForSync
- refactors syncFromPeers
The idea of refactoring is that we do not return on timeout anymore.

Change the strategy in syncFromPeers and waitForHeight

---

chain/consensus/mir/state_manager.go
go.mod

This PR:
-  Adds more information for debugging
- Uses timeout-based `waitForHeight` function
It addresses this test failure - https://app.circleci.com/pipelines/github/consensus-shipyard/lotus/353/workflows/f9712132-444c-49e3-8255-8d04991215e0
In the logs, we can see that one of the joined validators runs `syncFromPeers` function but never returns from it. 
There may be other reasons for the bug, and this fix probably does not fix the root cause.

Add timeout for waitfor block

---

scripts/ipc/run-subnet-docker.sh

```
ubuntu@ip-172-26-28-130:~/ipc/ipc-agent$ bin/ipc-infra/run-subnet-docker.sh 1240 1350 /root/t01003 ~/.ipc_agent/wallet.key
>>> Subnet /root/t01003 daemon running in container: be5a7ca5d7da0fbd41fdb206abdf6159338ef76c3e922e3bce4f4649ef2cd98c (friendly name: ipc_root_t01003_1240)
>>> Token to /root/t01003 daemon: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.K2Y5-FbhjBHfyRQ6lMOrKmrnsycvI6uRdS9muKYEPPU
>>> Default wallet: t1cp4q4lqsdhob23ysywffg2tvbmar5cshia4rweq
>>> Subnet subnet validator info:
t1cp4q4lqsdhob23ysywffg2tvbmar5cshia4rweq@/ip4/127.0.0.1/tcp/1347/p2p/12D3KooWJqyxkd5URfnB8jpoA1JK5E5Ld7CtjYTfEoTyWRWmHBiooHBio
>>> API listening in host port 1240
>>> Validator listening in host port 1350
ubuntu@ip-172-26-28-130:~/ipc/ipc-agent$ …
```

Fix validator-addr retrieval & container naming

---

.circleci/config.yml

This PR removes outdated targets from the circle CI config and uses Eudico version instead of Lotus version.

Fix CI flow

---

scripts/ipc/run-subnet-docker.sh

This formats the validator address output by eudico into the right format for later consumption by the ipc-agent. It's specific to the docker deployment, but so is the script. Nevertheless, we may or may not want to make the change. Discussion in https://github.com/consensus-shipyard/ipc-agent/pull/146#discussion_r1155139074

Print formatted validator address

---

chain/gen/genesis/f08_ipc_gateway.go

This PR fixes a bug for which the initial state for the `AppliedBottomUpNonce` was being set to `MaxInt` instead of `0`. After the actor refactor, this is expected to be `0` for the subsequent application of messages. 
This also introduces a new bug that will be fixed in a follow-up PR, where we should have a different account of applied nonces for each child subnet.

fix: bottom-up applied nonce initial state

---

.gitignore
Dockerfile
chain/consensus/compute_state.go
chain/gen/genesis/f08_ipc_gateway.go
eudico-core/genesis/genesis-test.json
eudico-core/genesis/genesis.json
scripts/ipc/src/subnet-daemon.sh
scripts/mir/daemon.sh
scripts/spacenet-genesis.sh

This PR is an excuse to open a quick discussion. So far, before we had cross-net messages, we provided some genesis funds to our test address to help with testing. We were funding the address with 5000FIL from genesis. Now that we have cross-net messages (and considering that the wallet key can be potentially leaked easily as is the one we are using for tests and in many tutorials). Should we reduce (or completely remove) these genesis funds even if that makes testing a bit harder for us as we would have to get funds from the faucet also? (practically we could also fund some other address manually with "significant" faucet funds).
This PR reduces the initial funds to 50FIL, should we reduce it more, leave it as-is, or remove them all the way?

Reduce initial funds to test address

---

build/bootstrap/spacenet.pi

Shouldn't have any immediate consequences but will be more robust against future infra changes.

Replace bootstrappers ip with dns

---

go.mod
go.sum
itests/ipc_test.go

Fixes https://github.com/consensus-shipyard/ipc-actors/pull/100 and depends on https://github.com/consensus-shipyard/ipc-actors/pull/100
It fixes an error for which checking if a validator had voted failed because there was a serialization problem when trying to inspect the submission state for checkpoints.

fix ValidatorHasVote so a validator can check it it has already voted

---

scripts/ipc/src/subnet-daemon.sh

This PR enables the EthRPC by default in the subnet IPC deployment scripts.

enable RPC API in bootstraps

---

cmd/eudico/daemon.go
cmd/lotus/eudico.go
eudico-core/fxmodules/invokes.go
itests/kit/ensemble.go

Several users (including ourselves) where experiencing weird behaviors when interacting with FEVM contracts that returned a variable and/or emitted an event. For some reason, the clients were getting stuck while waiting for the transaction receipt. 
The reason was that we weren't storing successfully in the ChainStore the events from FEVM contracts, so the client froze waiting for some new event related to the receipt to appear in the state. This PR fixes the problem.

Fixes a bug for which FEVM events weren't being stored

---

gateway/node.go

In Mir we don't use timestamps to identify blocks, which makes Lookback-related checks in the gateway to have unexpected behaviors. To avoid this, we rely on height diffs for lookback checks if we are using Mir as the consensus algorithm for the peer.

Rely on heightDiff instead of timestamp for Mir checks
