consensus-shipyard/lotus

build/params_spacenet.go, itests/kit/ensemble.go, itests/mir_test.go
=> fix: learner itests

.golangci.yml, chain/consensus/mir/cache_test.go, chain/consensus/mir/manager.go, chain/consensus/mir/state_manager.go, chain/consensus/mir/types.go, cmd/eudico/daemon.go, cmd/eudico/mirvalidator/checkpoint.go, cmd/eudico/mirvalidator/run.go, cmd/eudico/mirvalidator/utils.go, cmd/lotus/eudico.go, eudico-core/fxmodules/functional.go, eudico-core/fxmodules/rpcserver.go, itests/kit/ensemble.go, itests/kit/mir_db.go, itests/kit/mir_tools.go, itests/kit/node_miner.go
This PR fixes bugs and issues after refactoring.
=> Fix bugs and minor issues

chain/consensus/mir/manager.go, chain/consensus/mir/types.go, cmd/eudico/mirvalidator/checkpoint.go, cmd/eudico/mirvalidator/run.go, go.mod, go.sum
Before you mark the PR ready for review, please make sure that:
- example: ` fix: mempool: Introduce a cache for valid signatures`
- `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
- `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
=> Bump up Mir version to 0.2.1

node/impl/ipc/ipc.go
Deserializing from the CBORStore requires the original types to be registered in the CBOR atlas, but this is not the case for FVM actors state. In this case we need to deserialize the raw block and then use the specific type state to flag the deserializer the right type to use.
=> fix IPC actor state inspection and serialization

chain/consensus/mir/manager.go, chain/consensus/mir/state_manager.go, itests/kit/ensemble.go, itests/kit/mir_tools.go, itests/mir_test.go
This PR fixes https://github.com/consensus-shipyard/lotus/issues/79.
=> Fix issue 79

go.mod, go.sum
//cc @cryptoAtwill this should include you needed to test the ipc agent
=> Upgrade ipc bundle and related types

Dockerfile, cmd/eudico/genesis.go, cmd/eudico/mirvalidator/init.go, eudico-core/genesis/genesis.go, eudico-core/genesis/genesis.json, go.mod, go.sum, node/impl/ipc/ipc.go
- Fixes the genesis generation for subnets.
- Fixes some bugs in the way validators are added to the config file. 
- Adds some improvements to dockerfile
=> fix genesis and add validators

cmd/eudico/mirvalidator/cfg.go, cmd/eudico/mirvalidator/init.go, cmd/eudico/mirvalidator/run.go, cmd/eudico/mirvalidator/utils.go
This PR adds a LibP2P port to init CLI.
=> Add libp2p port

chain/consensus/iface.go, chain/consensus/mir/consensus.go, chain/consensus/mir/manager.go, chain/sub/incoming.go, scripts/mir/validator.sh
This PR removes unnecessary outdated checks, adds missed logging, and fixes Mir params.
=> Fix block validation and Mir params

go.mod, go.sum
This PR updated the version of Mir to 0.3.2.
=> Update mir 0.3.2

.circleci/config.yml, itests/mir_test.go
This PR:
- Adds more debug info and
- Increases timeout for reconfiguration tests
=> Add more debug info and increase timeout for reconfiguration tests

.circleci/config.yml
Set the environment variable for testing
=> Set env for testing

.circleci/config.yml, chain/consensus/mir/manager.go, chain/consensus/mir/pool/pool.go
This PR fixes the flow we stop components. There was a race between stopped components and we could not stop the Mir node properly and did not stop it at all.
=> WIP: Fix tests failures

go.mod, go.sum, scripts/ipc/README.md, scripts/ipc/run-root-docker-1val.sh, scripts/ipc/run-subnet-docker.sh
This PR includes minor fixes to the infra scripts and tags the new releases for Spacenet M1.
=> tag dependency releases for m1 release

.circleci/config.yml
This PR adds checks that the project can be built on macos and linux. It also uses caching.
=> WIP: add macos build

chain/gen/genesis/f08_ipc_gateway.go, go.mod, go.sum
Depends on actors version: https://github.com/consensus-shipyard/ipc-actors/pull/92
=> support to updated bundle with fixes

scripts/mir/4-node-net.sh, scripts/mir/validator.sh
This PR improves using environmental variables used for the Mir interceptor.
=> Fix env in scripts

e2e/.gitignore, e2e/docker-compose.yml, e2e/generator/generator.go, e2e/internal/fs/fs.go, e2e/internal/fs/fs_test.go, e2e/tests/tests.go, e2e/tests/utils.go, scripts/mir/node.sh
This PR fixes scripts to be able to run e2e tests.
=> Fix e2e scripts

chain/consensus/mir/manager.go, chain/consensus/mir/manager_test.go, chain/consensus/mir/membership/membership_test.go
This PR fixes https://github.com/consensus-shipyard/lotus/issues/166.
=> Fix issue 166

chain/consensus/mir/manager.go, chain/consensus/mir/manager_test.go
This PR adds logging and increases the timeout for reading membership.
=> Fix waitForMembership timeout

chain/consensus/mir/manager.go, chain/consensus/mir/manager_test.go, itests/mir_test.go
This PR fixes a minor bug in the test statement that led to that failure - https://app.circleci.com/pipelines/github/consensus-shipyard/lotus/767/workflows/9bd9e91b-b5ad-4823-8632-fddd1afc8e77
=> Fix height number threshold in a test

chain/consensus/mir/manager.go, chain/consensus/mir/manager_test.go
This PR fixes a minor bug in the tests.
=> Fix tests for membership Info

chain/consensus/mir/manager.go
Instead of crashing when a validator when the minimum number of validators hasn't been reached we should wait the same way we wait for our validator to be part of the membership set in the parent. This improves the UX and helps us preventing races in the deployment of infra for end-to-end testing.
=> Wait for minimum number of validators before crashing subnet validator

.circleci/config.yml
This PR removed the checking version from CI.
=> Disable version check in CI

cmd/eudico/main.go, cmd/eudico/mirvalidator/cfg.go
This PR partially fixes https://github.com/consensus-shipyard/lotus/issues/182 .
=> Expand OS path

go.mod, go.sum, itests/ipc_test.go, node/impl/ipc/ipc.go
This PR includes a new builtin bundle including changes in the IPC actors so `fund` and `release` can target a specific address in the subnet immediately above or below.
=> integrate new bundle with changes in fund/release

e2e/generator/generator.go
This PR fixes the e2e config generator.
=> Fix e2e generator

chain/consensus/mir/manager.go, chain/consensus/mir/membership/membership.go, chain/consensus/mir/membership/membership_test.go, chain/consensus/mir/state_manager.go, go.mod, go.sum, itests/kit/ensemble.go, itests/kit/mir_validator.go, itests/mir_test.go, scripts/ipc/mine-subnet.sh, scripts/ipc/src/subnet-daemon.sh
This PR fixes an error in error handling.
=> Fix error handling in Lotus
